### ISSUE TITLE
Make Parser Output consistent with template

### ISSUE THREAD

**Issue by mikaelmh** [CityOfNewYork/addressparser#7]
Template (specifies an array of locations after 'refLocation')

https://github.com/CityOfNewYork/CROL-WebApp/blob/master/template.ftl

**Comment by cds-amal** [comment]
The [template.ftl](https://raw.githubusercontent.com/CityOfNewYork/CROL-WebApp/master/src/template.ftl) needs to be updated. No occurrences of refLocation exists to be enriched as specified by the [Readme](https://github.com/CityOfNewYork/CROL-WebApp/#parsing-libraries)

Perhaps you could suggest what the JSON below **should** look like?

```
{
  "addresses": [
    {
      "refLocation": [
        {
          "@context": "http://schema.org", 
          "@type": "Place", 
          "address": {
            "@type": "PostalAddress", 
            "addressLocality": "New York City", 
            "addressRegion": "NY", 
            "borough": "MANHATTAN", 
            "postalCode": "10038", 
            "streetAddress": "66 JOHN STREET"
          }, 
          "geo": {
            "@type": "GeoCoordinates", 
            "latitude": 40.708787566436705, 
            "longitude": -74.00741944976967
          }
        }
      ]
    }, 
    {
      "refLocation": [
        {
          "@context": "http://schema.org", 
          "@type": "Place", 
          "address": {
            "@type": "PostalAddress", 
            "addressLocality": "New York City", 
            "addressRegion": "NY", 
            "borough": "MANHATTAN", 
            "postalCode": "10013", 
            "streetAddress": "132 MULBERRY STREET"
          }, 
          "geo": {
            "@type": "GeoCoordinates", 
            "latitude": 40.718386214929936, 
            "longitude": -73.9977778127041
          }
        }
      ]
    }
  ]
}
```

**Comment by mikaelmh** [comment]
My fault. As the parser output was wrong, we actually changed the template to be able to fit it.

The correct output should be like this;


"refLocation":[
    {
      "@type": "Place",
      "@context": "http://schema.org",
      "address": {
          "@type": "PostalAddress",
          "addressLocality": "New York City",
          "addressRegion": "NY",
          "postalCode": "11105",
          "streetAddress": "31-01 Ditmars Boulevard",
          "borough": "Queens" 
        },
      "geo": {
          "@type": "GeoCoordinates",
          "latitude": "40.776306",
          "longitude": "-73.910118"
        }
        }
      ]

**Comment by cds-amal** [comment]
Updated on heroku app, with validating JSON
